### ISSUE TITLE
Received size: duplicate number?

### ISSUE THREAD

**Issue by rpolve** [tremc/tremc#49]
Hi,

I hope it is not inappropriate to ask this here, but I don't understand why the received size information is duplicated in list view.

This also used to happen with transmission-remote-cli

![](https://user-images.githubusercontent.com/33606222/72521889-b0a56f00-385c-11ea-8910-000d033b0c4c.png)

**Comment by MatanZ** [comment]
The second number is the amount of data available. If at least one seed is known, then it does not appear, since all torrent is available. 

In your case only data that you have is available (either no other peers known, or all peers have only what you have), so the second number is equal to the first (what you have). In general, they can be different.
